# Generated by Django 3.0.3 on 2020-02-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='unit',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='quantity',
            name='num_of_product',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='unit',
            field=models.CharField(max_length=10),
        ),
    ]
